### ISSUE TITLE
Физика в игре

### ISSUE THREAD

**Issue by m-boyko** [bmstu-iu9/upt2019-12-starwars#14]
Потребовалось немного времени, чтобы понять, что физика в игре выходит за рамки простого притяжения кораблей к центру. Если верить открытым источникам, все гораздо сложнее: разработчики оригинала вели исследдовательскую работу и писали софт, который будет рассчитывать и визуализировать притяжение космических тел. 
Я посмотрела код оригинала и ничего не поняла. 
Не уверена, что смогу полностью повторить механику оригинала.

**Comment by tmible** [comment]
> Потребовалось немного времени, чтобы понять, что физика в игре выходит за рамки простого притяжения кораблей к центру. Если верить открытым источникам, все гораздо сложнее: разработчики оригинала вели исследдовательскую работу и писали софт, который будет рассчитывать и визуализировать притяжение космических тел.
> Я посмотрела код оригинала и ничего не поняла.
> Не уверена, что смогу полностью повторить механику оригинала.

Для начала надо понять, что там есть. Есть притяжение к центру. Есть движение вперёд, когда двигатель работает. Что ещё?

**Comment by Mazdaywik** [comment]
Сила притяжения к телу пропорциональна M/r², где M — масса звезды, а r — расстояние до неё. Вектор силы направлен на звезду.

Если (x, y) — координаты корабля, а (x′, y′) — координаты звезды, то проекции силы притяжения на оси координат будут

Fx′ = −(x−x′)/√r × G × m·M/r²
Fy′ = −(y−y′)/√r × G × m·M/r²
r = √((x−x′)² + (y−y′)²)

Здесь G — гравитационная постоянная, m — масса корабля. На самом деле, в модели можно для простоты считать G = 1, что эквивалентно рассмотрению G·M как некоторого коэффициента.

Соответственно, складываем силы притяжения каждой из звёзд и силу тяги ракеты по всем осям координат. (Силу тяги ракеты, вы, наверное, уже умеете считать.) Ускорения по осям координат — сила поделить на массу корабля:

ax = Fx/m
ay = Fy/m

Скорость корабля:

vx* = vx + ax·Δt
vy* = vy + ay·Δt

Координаты корабля:

x* = x + vx·Δt + ax·Δt²/2
y* = y = vy·Δt + ay·Δt²/2

Можно, конечно, воспользоваться более точным методом Рунге-Кутты, но не нужно.

Не знаю как у вас, но вообще, топливо космическому кораблю нужно только для того, чтобы _менять_ скорость: её величину и/или направление. Если двигатель корабля выключен, то он в отсутствии звёзд движется по инерции. В присутствии космических тел на него будут действовать силы тяготения. Тормозить корабль нечему — вакуум вокруг.

Чтобы затормозить со скорости v до нуля нужно столько же топлива, как и для разгона от нуля до той же скорости v. А чтобы повернуть на 90° не меняя скорости — в полтора раза больше топлива.

Вообще, формула Циолковского рулит. Сила, действующая на корабль, пропорциональна  произведению скорости (в м/с) потока газов на расход (в кг) в единицу времени:

F = u×dm/dt

Если считать, что скорость вытекающих газов не зависит от расхода топлива (а она как-то зависит на самом деле), то сила тяги получится пропорциональной расходу топлива.

**Comment by m-boyko** [comment]
@Mazdaywik Большое спасибо за такой развернутый ответ, Вы очень помогли! Постаралась реализовать описанные Вами вычисления в коде. Получилось создать физику, очень похожую на оригинал. Осталось только покрутить четыре константы: массу звезды, массы кораблей, и силу (извиняюсь, если использую неправильный термин) реактивной тяги. Прийти к балансу будет, наверное, самым трудным в этом вопросе.

У нас корабли могут находиться в двух состояниях: с включенным и выключенным двигателем.  Пока что топливо у них бесконечное. Но скоро мы это исправим!

**Comment by Mazdaywik** [comment]
Забыл в формулах выше указать гравитационную постоянную, обновил комментарий. На самом деле, при расчётах можно считать массу корабля m = 1 и гравитационную постоянную G = 1. Параметрами будут массы звёзд и реактивная тяга.

То, что мы считаем физическую константу G единицей для игрового мира нормально. Всё равно там не метры, а пиксели.

Кстати, проверка физической модели. Если взять вселенную с единственной звездой и кораблём с некоторым ненулевым начальным вектором скорости, то (а) при маленькой скорости корабль будет двигаться по эллиптической орбите, (б) при большой скорости улетать куда-то вдаль (по гиперболе-параболе-дуге большого эллипса). Причём в случае (а) звезда будет находиться в фокусе эллипса.

**Comment by Mazdaywik** [comment]
Реактивная тяга задаётся записывается как

F = u×**dm/dt**

Поэтому, если делать очень правдоподобно, заправленный корабль должен быть тяжелее и медленнее пустого. Поскольку масса корабля уменьшается. dm/dt. Огромная ракета на земле становится маленьким спутником на орбите. Бо́льшая часть массы ракеты — это топливо.

**Comment by tmible** [comment]
> Поэтому, если делать очень правдоподобно, заправленный корабль должен быть тяжелее и медленнее пустого. Поскольку масса корабля уменьшается. dm/dt. Огромная ракета на земле становится маленьким спутником на орбите. Бо́льшая часть массы ракеты — это топливо.

Ого, хорошая идея! @mortawe отложим на перспективу? Если будет время и желание покрыть проект позолотой и чтоб блестела.

**Comment by m-boyko** [comment]
@Mazdaywik 
> Если взять вселенную с единственной звездой и кораблём с некоторым ненулевым начальным вектором скорости, то (а) при маленькой скорости корабль будет двигаться по эллиптической орбите, (б) при большой скорости улетать куда-то вдаль (по гиперболе-параболе-дуге большого эллипса). Причём в случае (а) звезда будет находиться в фокусе эллипса.

Да, все именно так! 
Вот только небольшая особенность: корабль сначала приближается к звезде, потом, как только касается ее, отпрыгивает на некоторое расстояние. Это происходит несколько раз, после чего он отпрыгивает за пределы игрового экрана. Я  приняла это как ошибку в коде и исправила с помощью дополнительного условия (соприкосновение со звездой в любом случае должно означать смерть в игре). Или же у этого тоже есть объяснение? 

@tmible Да. Я напугана и заинтригована обилием потенциальной физики в этом проекте. Но топливный расход делаешь ты!

**Comment by tmible** [comment]
> @tmible Да. Я напугана и заинтригована обилием потенциальной физики в этом проекте. Но топливный расход делаешь ты!

@mortawe, отлично, добавляю карточку. Готов доделать всю физику вместо тебя хоть с этого момента

**Comment by Mazdaywik** [comment]
@mortawe, не представляю, почему корабль может отпрыгивать. Может быть, центр корабля попадает на центр звезды пиксель-в-пиксель и получается деление на нуль?

Баянчик вспомнился:

> На испытаниях Су-24 регулярно случался отказ аппаратуры бомбометания. Причем происходило это только в том случае, если на цель заходил летчик-испытатель Ильюшин. Причина оказалась в том, что только он заходил на цель с точностью, превышавшей машинную точность. Получался «машинный ноль», после чего шел сбой из-за попытки деления на ноль.

http://www.orator.ru/stories_istorii_o.html (подборка историй хоть и баянная, но почитать весело)

**Comment by m-boyko** [comment]
@Mazdaywik Нет, к сожалению это не деление на нуль, там проверка стоит =(
