### ISSUE TITLE
Зацикливание поля

### ISSUE THREAD

**Issue by m-boyko** [bmstu-iu9/upt2019-12-starwars#17]
при вылете кораблей с игрового поля они должны появляться с другой стороны
- [x] корабли
- [x] выстрелы
- [x] взрывы

**Comment by Mazdaywik** [comment]
На это интересно посмотреть с точки зрения физики. Гравитация звёзд заворачивается точно также? Т.е. если у левой границы экрана находится звезда, а корабль движется вдоль правой, тянет ли эта звезда его направо?

**Comment by m-boyko** [comment]
@Mazdaywik На данный момент не заворачивается. Просто при вылете за пределы игрового поля корабль перемещается на другой край, но сохраняет скорость. Звезда у нас одна, находится в центре квадратного поля. Как думаете, имеет смысл "завернуть" притяжение этой звезды? 

Можете посмотреть, как зацикливание пока что реализовано в черновом, но рабочем варианте. Ветка mortawe/looping, нужно запустить index.html
(Управление: a, d -  вращение левого корабля;  j, l - правого
s - реактивная тяга левого корабля; k - правого)
