### ISSUE TITLE
Баланс

### ISSUE THREAD

**Issue by m-boyko** [bmstu-iu9/upt2019-12-starwars#18]
- [x] мощность тяги нитро
- [x] масса звезды
- [x] масса кораблей (в.т.ч. масса топлива)
- [x] шаг вращения кораблей
- [x] скорость и направление выстрелов (в.т.ч. баг с самоуничтожением в момент выстрела)
- [x] стартовые позиции кораблей
- [x] скорость анимации фона

**Comment by tmible** [comment]
@mortawe скорость анимации фона, которую ты сделала тебя не устраивает?

**Comment by m-boyko** [comment]
@tmible меня устраивает, а пользователя? А тебя?

**Comment by tmible** [comment]
@mortawe мне нравится, а пользователя нет. Значит, настраиваемый сами

**Comment by m-boyko** [comment]
> @mortawe мне нравится, а пользователя нет. Значит, настраиваемый сами

Что насчёт стартовых позиций?

**Comment by tmible** [comment]
> Что насчёт стартовых позиций?

Не знаю, они тебя чем не устраивают?

**Comment by m-boyko** [comment]
> > Что насчёт стартовых позиций?
> 
> Не знаю, они тебя чем не устраивают?

Слишком близко к краю поля

**Comment by tmible** [comment]
> > > Что насчёт стартовых позиций?
> > 
> > 
> > Не знаю, они тебя чем не устраивают?
> 
> Слишком близко к краю поля

Насколько сдвинуть?

**Comment by m-boyko** [comment]
@tmible 
Как сказал Сергей Юрьевич, чем ближе к оригиналу - тем лучше. 
Можно измерить в процентном соотношении и клонировать к нам

**Comment by tmible** [comment]
> Можно измерить в процентном соотношении

Если тебе не лень, померь, и скажи мне -- я сдвину

**Comment by m-boyko** [comment]
@tmible 1:3
Но мне кажется в нашем масштабе это будет неоч. Но от краев отодвинуть нужно

**Comment by m-boyko** [comment]
Нужно увеличить скорость снарядов
