### ISSUE TITLE
Добавить загрузочный экран

### ISSUE THREAD

**Issue by tmible** [bmstu-iu9/upt2019-12-starwars#19]
Перед началом прорисовки игрового поля сделать загрузочный экран. Он должен содержать в себе название игры, её описание, инструкцию по управлению, <del>проработанный сюжет с неожиданной развязкой и двумя шутками про феминисток 4 волны</del> и упоминание разработчиков. Конечно, стилистика игры должна быть выдержана. По нажатию либо любой клавиши, либо одной конкретной экран должен пропадать, уступая место игровому полю.

**Comment by m-boyko** [comment]
Сделаем картино4ку или настоящим текстом бахнем?

**Comment by tmible** [comment]
> Сделаем картино4ку или настоящим текстом бахнем?

Зависит от шрифта

**Comment by m-boyko** [comment]
" @tmible  Раз уж мы переделали всю графику, то имеет смысл сделать загрузочный фон не изображением

**Comment by tmible** [comment]
От идеи отказались ввиду наличия README.md
