### ISSUE TITLE
Корабль взрывается от собственного выстрела

### ISSUE THREAD

**Issue by m-boyko** [bmstu-iu9/upt2019-12-starwars#29]
В ветке tmible/shots

**Comment by tmible** [comment]
Я знаю. Работаю над этим

**Comment by Mazdaywik** [comment]
В реальном мире эта проблема хорошо известна и давно решена. Взрыватели к снарядам имеют систему предохранения, предотвращающую срабатывание взрывателя при служебном обращении и начальном участке траектории. Подробнее можно почитать здесь:

http://library.bmstu.ru/L2kFX/l2kfx_fs_32549.aspx/Козлов%20В.И.%20Особенности%20конструкции%20взрывательных%20устройств%20к%20боеприпасам%20ствольной%20артиллерии%20и%20ракетным%20снарядам.%202012г.pdf

Я учился на кафедре СМ5, у нас курс взрывателей читал автор этого учебника. Этот курс сложно было сдать выше чем на тройку, но сравнительно просто было пересдать на повышение отметки перед дипломом. Поскольку на такой пересдаче Козлов спрашивал только РГМ-6 — лучший взрыватель Второй мировой войны. И довольно интересно устроенный (рисунок 4.1 на стр. 55 по ссылке выше).

Вот ещё ссылка про РГМ-6: http://engineering-science.ru/doc/452096.html

Не могу не вспоминать этот курс. У всех выпускников СМ5, кто учился у Козлова (он умер несколько лет назад), этот курс остаётся в голове навсегда.

**Comment by tmible** [comment]
@Mazdaywik ☹️
![image](https://user-images.githubusercontent.com/52622566/63264080-dff68680-c292-11e9-8767-24a5b19094c1.png)

А есть альтернативные способы? Хоть я уже и настроил скорость снаряда и взорваться непреднамеренно сразу после выстрела теперь можно только если разогнаться до большой скорости и стрелять назад, хочу глянуть.

**Comment by Mazdaywik** [comment]
Предыдущий комментарий представлял собой лирическое отступление. Просто вспомнил курс по взрывателям. Снаряды не должны взрываться во время выстрела (а в пушках там просто огромные перегрузки), но должны надёжно срабатывать по цели.

А для снаряда в программе можно сохранять момент рождения и запретить ему взрываться раньше, чем через n микросекунд, например.

Нарушаю авторские права:
* [Козлов В.И. Особенности конструкции взрывательных устройств к боеприпасам ствольной артиллерии и ракетным снарядам. 2012г.pdf](https://github.com/bmstu-iu9/upt2019-12-starwars/files/3515854/2012.pdf)

**Comment by tmible** [comment]
@Mazdaywik я думал, требовать задержку с момента выстрела — плохое решение... не изящное что ли 😕. Я просто вынес место появления той самой взрывоопасной точки за пределы контура корабля и начал учитывать мгновенную скорость корабля в момент выстрела, как для самолётов рассчитывают.

Спасибо за учебник! Почитаю на досуге

**Comment by Mazdaywik** [comment]
В реальных взрывателях часто учитываются силы инерции: перегрузки в момент выстрела и центробежная сила, если снаряд вращается (нарезное орудие или турбореактивный снаряд). Вот хорошая схема:

![Взрыватель М4](https://studfiles.net/html/2706/408/html_txNwUKuLff.JuvP/img-V4_LVJ.png)

[Оригинал, крупно](https://studfiles.net/html/2706/408/html_txNwUKuLff.JuvP/img-V4_LVJ.png)

В невзведённом состоянии жало ударника 8 упрятано во втулке 14 и никак не касается капсюля-воспламенителя 21. В момент выстрела под действием перегрузок опускается гильза 10, выкатывается верхний шарик 7. В этот момент гильза всё ещё удерживает шарики 7, которые блокируют движение ударника 8. Когда снаряд отлетел достаточно далеко от гранатомёта¹, гильза 10 поднимается, высвобождает оставшиеся шарики. Взрыватель взводится — поднимается ударник 8, сдвигается пружиной 22 капсюль-воспламенитель 21 под жало. В момент столкновения с целью жало накалывает капсюль-воспламенитель 21, тот взрывает капсюль-детонатор 20, тот — детонатор 18, а тот — снаряд (на рисунке не показан, он подразумевается)

¹ Почему гранатомёт? Гильза двигается зигзагообразно (прерывистое движение взводящей детали) — перегрузки небольшие и длительные. В пушках перегрузки короткие и высокие, поэтому зигзагообразный паз там не делают. Взрыватель головной, значит, снаряд кумулятивный. Взрыватель может срабатывать при попадании в грунт (см. рисунок г), что тоже характерная особенность взрывателей для гранат.

Чтобы взрыватель взвёлся, гильза должна, во-первых, дойти до упора вниз (отпустить один шарик), а потом вверх (отпустить другие шарики). Так обеспечивается временна́я задержка, обеспечивающая безопасность стреляющего. Заметьте, если в положении б снаряд встретится с преградой, то взрыватель не сработает.

Эту картинку мне выдал Яндекс по запросу «взрыватели». Я не знаю, что находится на той странице, откуда картинка взята. Писал по памяти, вспоминал лабы по Козлову.

**Comment by Mazdaywik** [comment]
Забыл добавить. Обратите внимание на картинку _в._ Ударник не выступает наружу корпуса. Это важно. Взрыватель сработает по броне, когда и корпус сомнётся, и жало ударника наколет капсюль-воспламенитель. Он сработает и по грунту, если промажет — грунт насыпется в лунку и надавит на ударник. А по сетке или кустам не сработает.

Интересно, а какие вы предметы будете вспоминать с ностальгией?..
