### ISSUE TITLE
Форматирование кода

### ISSUE THREAD

**Issue by m-boyko** [bmstu-iu9/upt2019-12-starwars#3]
Табуляции или пробелы?

**Comment by m-boyko** [comment]
![image](https://user-images.githubusercontent.com/53974734/62958152-c969ae80-bdfe-11e9-8517-ec9eff465bbf.png)
Придерживаемся этих рекомендаций. Фигурную скобку оставляем на строке. Сейчас есть недочеты, в процессе работы их исправим. На финишной прямой получим отформатированный в одном стиле код.

**Comment by tmible** [comment]
Согласен на всё, кроме отступа в 2 пробела. Хочу в 4!

**Comment by m-boyko** [comment]
@tmible Две табуляции?

**Comment by tmible** [comment]
> @tmible Две табуляции?

@mortawe нет. 1 таб = 4 пробела

**Comment by m-boyko** [comment]
@tmible Какие подводные камни у совместного использования табуляций и пробелов в отступах?

**Comment by tmible** [comment]
> @tmible Какие подводные камни у совместного использования табуляций и пробелов в отступах?

@mortawe не надо пробелы в отступах в начале строки использовать. Ты в атоме пишешь?

**Comment by m-boyko** [comment]
@tmible да

**Comment by tmible** [comment]
@mortave в настройках поставь длину табуляции 4
