### ISSUE TITLE
Топливо и количество выстрелов делаем конечными?

### ISSUE THREAD

**Issue by tmible** [bmstu-iu9/upt2019-12-starwars#5]

**Comment by m-boyko** [comment]
Да, конечно. Это добавит в игру сложность, которая есть в оригинале. 
Вот только топливо для выстрелов и для нитро будет общим или раздельным?

**Comment by tmible** [comment]
> Да, конечно. Это добавит в игру сложность, которая есть в оригинале.
> Вот только топливо для выстрелов и для нитро будет общим или раздельным?

Конечно, раздельным

**Comment by m-boyko** [comment]
Посмотрела оригинал, там действительно раздельные ресурсы.
